# Generated by Django 3.0.8 on 2020-10-01 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDetecion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detectType', models.IntegerField(blank=True, default=0, null=True, verbose_name='타겟 종류')),
                ('xmin', models.IntegerField(blank=True, default=0, null=True, verbose_name='xmin')),
                ('ymin', models.IntegerField(blank=True, default=0, null=True, verbose_name='ymin')),
                ('xmax', models.IntegerField(blank=True, default=0, null=True, verbose_name='xmax')),
                ('ymax', models.IntegerField(blank=True, default=0, null=True, verbose_name='ymax')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='탐지 생성일')),
            ],
            options={
                'verbose_name': '탐지 결과',
                'verbose_name_plural': '탐지 결과',
            },
        ),
        migrations.CreateModel(
            name='TargetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=254, unique=True, verbose_name='이미지 파일 경로')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='파일 생성일')),
            ],
            options={
                'verbose_name': '원본 이미지',
                'verbose_name_plural': '원본 이미지',
            },
        ),
    ]
