# Generated by Django 3.0.8 on 2020-10-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hwInfo', '0001_initial'),
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetimage',
            name='target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwInfo.Product', verbose_name='대상 기기'),
        ),
        migrations.AddField(
            model_name='targetdetecion',
            name='targetImage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='detect.TargetImage', verbose_name='대상 이미지'),
        ),
    ]
