# Generated by Django 3.0.8 on 2020-10-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20201001_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetDetecion',
            new_name='TargetDetection',
        ),
    ]
