# Generated by Django 3.0.8 on 2020-10-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_auto_20201002_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetdetection',
            name='targetImage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_detection', to='detect.TargetImage', verbose_name='대상 이미지'),
        ),
    ]
