# Generated by Django 3.0.8 on 2020-10-16 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hwInfo', '0003_location_altvalue'),
        ('detect', '0005_targetdetection_isupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageRaw', models.TextField()),
                ('width', models.FloatField(blank=True, default=0, null=True, verbose_name='xmin')),
                ('height', models.FloatField(blank=True, default=0, null=True, verbose_name='xmin')),
                ('xmin', models.FloatField(blank=True, default=0, null=True, verbose_name='xmin')),
                ('ymin', models.FloatField(blank=True, default=0, null=True, verbose_name='ymin')),
                ('xmax', models.FloatField(blank=True, default=0, null=True, verbose_name='xmax')),
                ('ymax', models.FloatField(blank=True, default=0, null=True, verbose_name='ymax')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='탐지 생성일')),
                ('detectType', models.IntegerField(blank=True, default=0, null=True, verbose_name='타겟 종류')),
                ('isUpdated', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwInfo.Product', verbose_name='대상 기기')),
            ],
            options={
                'verbose_name': '탐지 결과 (새 모델)',
                'verbose_name_plural': '탐지 결과 (새 모델)',
            },
        ),
    ]
