# Generated by Django 3.0.8 on 2020-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_detectioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetimage',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
