# Generated by Django 3.0.8 on 2020-10-01 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hwInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='영상 파일 이름')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='파일 생성일')),
                ('target', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwInfo.Product', verbose_name='대상 기기')),
            ],
            options={
                'verbose_name': '열화상 영상',
                'verbose_name_plural': '열화상 영상',
            },
        ),
        migrations.CreateModel(
            name='StreamRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='영상 파일 이름')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='파일 생성일')),
                ('target', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwInfo.Product', verbose_name='대상 기기')),
            ],
            options={
                'verbose_name': '실화상 영상',
                'verbose_name_plural': '실화상 영상',
            },
        ),
    ]
