# Generated by Django 3.0.8 on 2020-10-12 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwInfo', '0002_auto_20201001_1350'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamrecord',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hwInfo.Product', verbose_name='대상 기기'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticrecord',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwInfo.Product', verbose_name='대상 기기'),
        ),
    ]
