# Generated by Django 3.0.8 on 2020-10-01 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hwInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(20,), **{}), max_length=20, unique=True, verbose_name='스트리밍 접근 키')),
                ('isActive', models.BooleanField(default=False, verbose_name='스트리밍 상태')),
                ('startedAt', models.DateTimeField(blank=True, null=True, verbose_name='스트리밍 시작 일시')),
                ('finishedAt', models.DateTimeField(blank=True, null=True, verbose_name='스트리밍 종료 일시')),
                ('target', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='hwInfo.Product', verbose_name='스트리밍 대상 기기')),
            ],
            options={
                'verbose_name': '스트리밍 상태',
                'verbose_name_plural': '스트리밍 상태',
            },
        ),
    ]
