# Generated by Django 3.0.8 on 2020-10-01 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cordinateX', models.FloatField(blank=True, max_length=50, verbose_name='x좌표')),
                ('cordinateY', models.FloatField(blank=True, max_length=50, verbose_name='y좌표')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='최신 위치')),
            ],
            options={
                'verbose_name': 'GPS',
                'verbose_name_plural': 'GPS',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='기기 명')),
                ('mac', models.CharField(max_length=200, unique=True, verbose_name='기기 MAC 주소')),
                ('authKey', models.CharField(blank=True, max_length=20, null=True, verbose_name='인증 키')),
                ('isPower', models.BooleanField(default=False, verbose_name='전원 상태')),
                ('isActive', models.BooleanField(default=False, verbose_name='기기 활성화')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='기기 생성일')),
                ('activeAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='기기 등록일')),
                ('isPower_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='전원 상태 업데이트 일시')),
            ],
            options={
                'verbose_name': '제품(카메라) 상태',
                'verbose_name_plural': '제품(카메라) 상태',
            },
        ),
    ]
