# Generated by Django 3.0.8 on 2020-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwInfo', '0003_location_altvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='altValue',
            field=models.FloatField(blank=True, default=0, verbose_name='고도'),
        ),
    ]
